# Generated by Django 5.2.1 on 2025-06-04 07:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('type', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=100)),
                ('aired', models.DateTimeField(default='2000-01-01')),
                ('status', models.CharField(max_length=100)),
                ('genre', models.CharField(default='Action', max_length=100)),
                ('premiered', models.DateTimeField(auto_now_add=True, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=1440))),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime_covers/')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('quality', models.CharField(choices=[('HD', 'High Definition'), ('SD', 'Standard Definition'), ('4K', 'Ultra HD')], default='HD', max_length=100)),
            ],
            options={
                'ordering': ['-premiered'],
            },
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
