# Generated by Django 5.2.1 on 2025-06-04 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_animecatalog_delete_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecatalog',
            name='aired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='animecatalog',
            name='premiered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
