# Generated by Django 5.2.1 on 2025-07-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_animecatalog_aired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animecatalog',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
